name: fullstack_todo_arcade
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  arcade: ^0.1.2
  dargon2: ^3.2.1
  dart_jsonwebtoken: ^2.12.1
  envied: ^0.5.2
  fullstack_todo_shared:
    path: ../fullstack_todo_shared
  get_it: ^7.6.4
  goose: ^0.1.0
  injectable: ^2.3.2
  luthor: ^0.2.2
  postgres: ^3.0.4
  supertypes: ^0.0.5

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  injectable_generator: ^2.4.1
  lint: ^2.3.0
  supertypes_generator: ^0.0.7
  test: ^1.25.0
